[project]
name = "homelab"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ansible==11.7.0",
    "fastapi[standard]>=0.115.14",
    "pre-commit>=4.2.0",
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=6.0.2,<7.0.0",
    "sqlmodel>=0.0.24",
]
